config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :enquiries, only: [:new, :create] do 
    collection { get :thanks }
  end
  resources :brands

  #index: all your previous orders
  resources :orders, only: [:index, :show] do 
    # get :shipping_method, path: "shipping"
    # get :summary
    # post :go_back
    # get :express_checkout
    # get :purchase
  end
  
  resource :carts, path: 'cart', only: [:show] do
    resources :items, controller: :cart_items, only: [:create, :update, :destroy]
    collection do
      get :previous
      get :checkout
      post :update_checkout
      get :express_checkout
      post :paypal_finish
    end
  end
  

  #user account paths
  scope module: :user_system do
    resources :users, path: "user", except: [:index, :destroy]
    resources :sessions, only: [:new, :create, :destroy] do
      collection { get :get_user_id }
    end
    resources :account_activations, only: :edit
    resources :password_resets, except: [:index, :show, :destroy]
  end

  #admin paths
  namespace :admin do
    resources :settings
    resources :sites
    resources :pages, except: :show
    resources :categories, only: :index
    resources :products, only: :index do
      collection do
        get :amazon
      end
      member do
        get :ebay
      end
    end
    resources :users, except: :show
    resources :categories, except: :show
    resources :products, except: :show do
      collection do
        get :pull_from_amazon
        post :check_generated_report_id
        get :process_generated_report
      end
    end
    resources :orders do
      collection { get :manage }
      member do
        get :print
        get :complete_order
        get :flag
        get :resolve_flag
        get :duplicate
        get :resend_emails
      end
      resources :notes
    end

  end

  
  resources :products, only: [:index, :show]
  resources :categories, only: [:index, :show]


  get    'signup'  => 'user_system/users#new'
  get    'login'   => 'user_system/sessions#new'
  post   'login'   => 'user_system/sessions#create'
  delete 'logout'  => 'user_system/sessions#destroy'

  post    'activate_admin' => 'user_system/sessions#admin_visible_toggle'
  post    'admin/remove_image' => 'admin/products#remove_image'

  get 'feeds'=> 'static_pages#feeds' 

  post 'uploads' => 'images#upload'

  root 'pages#show'
  resources :pages, path: "", only: :show

end

app/views/admin/pages/_form.html.haml
= form_for([:admin, @page]) do |f|
  = errors @page, f

  = f.hidden_field :id

  #two_panel_form
    #main_panel
      .field
        = f.label :name
        = f.text_field :name

      .field
        = f.label :body
        = f.cktext_area :body, class: 'editable'
    #side_panel
      .field.check_box_field
        = f.label :published do
          = f.check_box :published
          %span Published

      .field
        = f.label :page_title
        = f.text_field :page_title

      .field
        = f.label :banner
        = f.file_field :banner

      .field
        = f.label :meta_description
        = f.text_area :meta_description, rows: 6

      .field
        = f.label :site_id
        = f.collection_select :site_id, Site.all, :id, :name

  .actions
    = f.submit

app/views/admin/pages/_section_bar.html.haml
- content_for :buttons do
  = link_to "All Pages", admin_pages_path
  = link_to "Add Page", new_admin_page_path

app/views/admin/pages/edit.html.haml
- provide :title, "Edit Page"
= render 'section_bar'
= render 'form'

app/views/admin/pages/index.html.haml
- provide :title, "Content"
= render 'section_bar'


%table
  %thead
    %tr
      %th Name
      %th Published
      %th
      %th
      %th

  %tbody
    - @pages.each do |page|
      %tr{class: cycle("odd", "even")}
        %td= page.name
        %td= page.published ? "Yes" : "No"
        %td= page.site.try(:name)
        %td.admin_index_action= link_to 'Edit', edit_admin_page_path(page.id)
        %td.admin_index_action= link_to 'Destroy', [:admin, page], :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/admin/pages/new.html.haml
- provide :title, "New Page"
= render 'section_bar'
= render 'form'