config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :enquiries, only: [:new, :create] do 
    collection { get :thanks }
  end
  resources :brands

  #index: all your previous orders
  resources :orders, only: [:index, :show] do 
    # get :shipping_method, path: "shipping"
    # get :summary
    # post :go_back
    # get :express_checkout
    # get :purchase
  end
  
  resource :carts, path: 'cart', only: [:show] do
    resources :items, controller: :cart_items, only: [:create, :update, :destroy]
    collection do
      get :previous
      get :checkout
      post :update_checkout
      get :express_checkout
      post :paypal_finish
    end
  end
  

  #user account paths
  scope module: :user_system do
    resources :users, path: "user", except: [:index, :destroy]
    resources :sessions, only: [:new, :create, :destroy] do
      collection { get :get_user_id }
    end
    resources :account_activations, only: :edit
    resources :password_resets, except: [:index, :show, :destroy]
  end

  #admin paths
  namespace :admin do
    resources :settings
    resources :sites
    resources :pages, except: :show
    resources :categories, only: :index
    resources :products, only: :index do
      collection do
        get :amazon
      end
      member do
        get :ebay
      end
    end
    resources :users, except: :show
    resources :categories, except: :show
    resources :products, except: :show do
      collection do
        get :pull_from_amazon
        post :check_generated_report_id
        get :process_generated_report
      end
    end
    resources :orders do
      collection { get :manage }
      member do
        get :print
        get :complete_order
        get :flag
        get :resolve_flag
        get :duplicate
        get :resend_emails
      end
      resources :notes
    end

  end

  
  resources :products, only: [:index, :show]
  resources :categories, only: [:index, :show]


  get    'signup'  => 'user_system/users#new'
  get    'login'   => 'user_system/sessions#new'
  post   'login'   => 'user_system/sessions#create'
  delete 'logout'  => 'user_system/sessions#destroy'

  post    'activate_admin' => 'user_system/sessions#admin_visible_toggle'
  post    'admin/remove_image' => 'admin/products#remove_image'

  get 'feeds'=> 'static_pages#feeds' 

  post 'uploads' => 'images#upload'

  root 'pages#show'
  resources :pages, path: "", only: :show

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :delivery_service
  belongs_to :user
  has_many :order_items
  accepts_nested_attributes_for :order_items, allow_destroy: true
  has_many :products, through: :order_items
  has_many :notes
  accepts_nested_attributes_for :notes, :reject_if => lambda { |a| a[:body].blank? }

  belongs_to :shipping_address, class_name: 'Address'
  belongs_to :billing_address, class_name: 'Address'


  default_scope -> { order created_at: :desc }

  scope :pending, -> { unscoped.awaiting_payment }
  scope :unprocessed, -> { awaiting_dispatch }
  scope :processed, -> { unscoped.dispatched }
  scope :ended, -> { unscoped.cancelled }
  scope :all_, -> { unscoped.order(created_at: :desc) }

  scope :flagged, -> { all_.where.not(flag: nil) }
  scope :issues, -> { all_.issue_raised }
  scope :resolved, -> { all_.resolved }

  enum order_status: [:cart, :pending, :processing, :complete]
  enum payment_type: [:standard, :free]
  enum shipping_type: [:paypal, :sagepay]
  enum flag: [:issue_raised, :resolved]

  def empty?
    order_items.empty?
  end

  def has_items?
    total_items > 0
  end

  def total_items
    order_items.inject(0) { |t, i| t + i.quantity }
  end

  def total_before_tax
    order_items.inject(0.0) { |t, i| t + i.sub_total }
  end

  def tax
    order_items.inject(0.0) { |t, i| t + i.tax_amount }
  end

  def total_price
    total_before_tax + tax + shipping_cost
  end
  def total_price_in_pence
    (self.total_price*100).to_int
  end

  def shipping_cost
    delivery_service.try(:price) || 0
  end

  def flagged?
    issue_raised? || resolved?
  end

  def locked?
    processing? || complete?
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :print, :dispatch_order, :update_tracking, :flag, :resolve_flag, :duplicate, :resend_emails]

  def index
    @orders = Order.where.not(purchased_at: nil)
  end

  def manage
    @order = Order.find_by(id: params[:order_id]) || Order.new
  end

  def print
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      @order.pending!
      redirect_to manage_admin_orders_path(order_id: @order)
      flash[notice] = 'Order was successfully created.'
    else
      render :new
    end
  end

  def update
    if @order.update(order_params)
      redirect_to manage_admin_orders_path(order_id: @order)
      flash[notice] = 'Order was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @order.destroy
    redirect_to admin_orders_url, notice: 'Order was successfully destroyed.'
  rescue
    redirect_to admin_orders_url, notice: 'Cannot delete order, order item etyc.'
  end

  def flag
    @order.issue_raised!
    redirect_to manage_admin_orders_path(order_id: @order)
  end

  def resolve_flag
    @order.resolved!
    redirect_to manage_admin_orders_path(order_id: @order)
  end

  def resend_emails
    OrderMailer.notify_signline(@order).deliver_now
    OrderMailer.notify_buyer(@order).deliver_now
    redirect_to manage_admin_orders_path(order_id: @order), notice: 'Emails sent'
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(
        :first_name, :last_name, :company, :billing_address_id, :email_address, :phone_number, :status, :received_at,
        :accepted_at, :shipped_at, :delivery_service_id, :delivery_price, :delivery_cost_price, :delivery_tax_rate,
        :delivery_tax_amount, :accepted_by, :shipped_by, :consignment_number, :rejected_at, :rejected_by,
        :ip_address, :separate_delivery_address, :shipping_address_id, :amount_paid, :exported, :invoice_number, :payment_method,
        :customer_id, :sales_channel, :tracking_details, order_items_attributes: [:id, :product_id, :quantity, :unit_price, :tax_rate],
        notes_attributes: [:id, :body, :user_id]
    )
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_cart, only: [:new, :create, :update]

  def index
    @orders = Order.all
  end


  # POST /orders
  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(@cart)
    if @order.save
      @order.set_step "checkout"
      session[:order_id] = @order.id
      @order.set_billing_as_shipping if params[:order][:ship_to_billing_address]
      checkout_navigation
      set_up_user
    else
      @order.build_billing_address unless @order.billing_address
      @order.build_shipping_address unless @order.shipping_address
      render :new
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

end

app/views/admin/orders/_address.html.haml
= raw(address.try(:full_address)) || "No address"

app/views/admin/orders/_order_item_fields.haml
%tr
  %td= f.collection_select :product_id, Product.all, :id, :sku
  %td= f.text_field :quantity, placeholder: 'Quantity'
  %td= f.text_field :unit_price, placeholder: 'Price'
  %td= f.text_field :tax_rate, placeholder: 'Tax'

app/views/admin/orders/_section_bar.html.haml
- content_for :buttons do
  = link_to "All Orders", admin_orders_path
  = link_to "Add Order", manage_admin_orders_path

app/views/admin/orders/index.html.haml
- provide :title, "Orders"
= render 'section_bar'

%table
  %thead
    %tr
      %th ID
      %th Amount
      %th Purchased Date
      %th

  %tbody
    - @orders.each do |order|
      %tr{class: cycle("odd", "even")}
        %td= order.id
        %td= order.amount
        %td= order.purchased_at.try{strftime("%d %b. %Y")}
        %td= link_to "Show", manage_admin_orders_path(order_id: order)

app/views/admin/orders/manage.html.haml
- provide :title, "All Orders"
= render 'section_bar'

#admin_content
  #order_actions
    - unless @order.new_record?

      - if @order.flagged? && !@order.resolved?
        = link_to(fa_icon("flag", text: "Resolve Flag"), resolve_flag_admin_order_path(@order))
      - else
        = link_to(fa_icon("flag-o", text: "Flag Order"), flag_admin_order_path(@order))

      //= link_to "Complete Order", complete_order_admin_order_path(@order) unless @order.complete?
      = link_to "Print", "javascript:frames['frame'].print()", class: 'minor_button'
      = link_to "Resend Emails", resend_emails_admin_order_path(@order)
      //= link_to 'Duplicate', duplicate_admin_order_path(@order)
      %iframe.hidden{src: print_admin_order_path(@order), name: "frame"}
  = form_for [:admin, @order] do |f|
    = errors @order, f
    #admin_form_wrapper
      #left_form_wrapper
        = field_set_tag 'Line Items' do
          %table#more_order_items
            %tr
              %th Product
              %th
              %th
              %th Price
            =  f.fields_for :order_items do |ff|
              %tr
                %td.thumbnail_cell= image_tag(ff.object.channel_thumnail, class: 'manage_order_image')
                %td.no_wrap= "#{ff.object.quantity} x"
                %td
                  = "#{ff.object.name}"
                %td= number_to_currency ff.object.unit_price

          = link_to_add_fields "+ Add Item", f, :order_items, "button add_fields", "BLAH" unless @order.locked?
          %table.order_totals_table
            %tr
              %td Subtotal
              %td= number_to_currency @order.total_before_tax
            %tr
              %td Shipping
              %td= number_to_currency @order.shipping_cost
            %tr
              %td VAT
              %td= number_to_currency @order.tax
            %tr.order_total_row
              %td Total
              %td= number_to_currency @order.total_price

        = field_set_tag 'Shipping' do

          .field
            = f.label :delivery_service_id
            = f.collection_select :delivery_service_id, DeliveryService.all, :id, :select_display

        = field_set_tag 'Payment' do
          .field
            = f.label :payment_method
            = f.select :payment_method, ["Paypal", "Card", "Cash", "Cheque", "Bank Transfer"], include_blank: "-- Please Select --"

        = field_set_tag 'Admin' do

          - if !@order.new_record? && @order.shipped_at
            .field
              = f.label :shipped_at
              %p= @order.shipped_at
          .field
            = f.label :order_status
            = f.select :order_status, Order.order_statuses.map{|k, v| [k.humanize , k]}





      #right_form_wrapper
        = field_set_tag 'Customer' do
          = f.collection_select :user_id, User.all, :id, :name, prompt: '-- Please Select --'
          .field
            = f.label :name
            = f.text_field :name
          .field
            = f.label :email
            = f.text_field :email



        = field_set_tag 'Billing Address', id: 'billing_address' do
          //= f.hidden_field :billing_address_id
          //= link_to "Edit", new_admin_address_path(order_id: @order.id, address_type: 'billing'), remote: true
          #billing_address
            = render 'address', address: @order.billing_address




        = field_set_tag 'Shipping Address', id: 'delivery_address' do
          = f.label :same_shipping_address, "Deliver to an alternate address"
          = f.check_box :same_shipping_address

          #delivery_address_optional_container
            //= f.hidden_field :shipping_address_id
            //= link_to "Edit", new_admin_address_path(order_id: @order.id, address_type: 'shipping'), remote: true
            #shipping_address
              = render 'address', address: @order.shipping_address

    .actions
      = f.submit 'Save'

app/views/admin/orders/print.html.haml
#print_page
  .header
    = image_tag 'logo.png'
    .order
      = @order.id


  = field_set_tag 'Order' do
    .left_group
      .order_summary
        %p
          %b Order Placed:
          = @order.created_at
          %br
          %b Order Total:
          = number_to_currency @order.total_price

    %table
      %tr
        %th Product
        %th
        %th
        %th Price
      - @order.order_items.each do |item|
        %tr
          %td= image_tag item.channel_thumnail
          %td.no_wrap= "#{item.quantity} x"
          %td
            %span
              = item.name
          %td= number_to_currency item.unit_price
  = field_set_tag 'Shipping Details', class: 'shipping_details' do
    .left_group
      %p
        .address
          - unless @order.same_shipping_address?
            = raw @order.shipping_address.try(:full_address)
          - else
            = raw @order.billing_address.try(:full_address)

    .right_group
      %p
        %b Shipping Service:
        %br
        = @order.delivery_service.try(:name)
      %table.order_totals_table
        %tr
          %td Subtotal
          %td= number_to_currency @order.total_before_tax
        %tr
          %td Shipping
          %td= number_to_currency @order.shipping_cost
        //%tr
        //  %td VAT
        //  %td= number_to_currency @order.tax
        %tr.order_total_row
          %td Total
          %td= number_to_currency @order.total_price


  #split_fieldset_holder
    = field_set_tag 'Payment Details', class: 'split_fieldsets' do
      .left_group
        %p
          %b Payment Method:
          %br
          = @order.payment_method
        %p
          %b Billing Address
          %br
            = raw @order.billing_address.try(:full_address)

    = field_set_tag 'Customer Details', class: 'split_fieldsets' do
      %p
        %b Name
        %br/
        = @order.name
      %p
        %b Email
        %br/
        = "#{@order.email}"
      %p
        %b Phone
        %br/
        = "#{@order.phone}"