config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :enquiries, only: [:new, :create] do 
    collection { get :thanks }
  end
  resources :brands

  #index: all your previous orders
  resources :orders, only: [:index, :show] do 
    # get :shipping_method, path: "shipping"
    # get :summary
    # post :go_back
    # get :express_checkout
    # get :purchase
  end
  
  resource :carts, path: 'cart', only: [:show] do
    resources :items, controller: :cart_items, only: [:create, :update, :destroy]
    collection do
      get :previous
      get :checkout
      post :update_checkout
      get :express_checkout
      post :paypal_finish
    end
  end
  

  #user account paths
  scope module: :user_system do
    resources :users, path: "user", except: [:index, :destroy]
    resources :sessions, only: [:new, :create, :destroy] do
      collection { get :get_user_id }
    end
    resources :account_activations, only: :edit
    resources :password_resets, except: [:index, :show, :destroy]
  end

  #admin paths
  namespace :admin do
    resources :settings
    resources :sites
    resources :pages, except: :show
    resources :categories, only: :index
    resources :products, only: :index do
      collection do
        get :amazon
      end
      member do
        get :ebay
      end
    end
    resources :users, except: :show
    resources :categories, except: :show
    resources :products, except: :show do
      collection do
        get :pull_from_amazon
        post :check_generated_report_id
        get :process_generated_report
      end
    end
    resources :orders do
      collection { get :manage }
      member do
        get :print
        get :complete_order
        get :flag
        get :resolve_flag
        get :duplicate
        get :resend_emails
      end
      resources :notes
    end

  end

  
  resources :products, only: [:index, :show]
  resources :categories, only: [:index, :show]


  get    'signup'  => 'user_system/users#new'
  get    'login'   => 'user_system/sessions#new'
  post   'login'   => 'user_system/sessions#create'
  delete 'logout'  => 'user_system/sessions#destroy'

  post    'activate_admin' => 'user_system/sessions#admin_visible_toggle'
  post    'admin/remove_image' => 'admin/products#remove_image'

  get 'feeds'=> 'static_pages#feeds' 

  post 'uploads' => 'images#upload'

  root 'pages#show'
  resources :pages, path: "", only: :show

end

app/models/brand.rb
class Brand < ActiveRecord::Base

  has_many :products
  has_many :site_categories
  has_many :sites, through: :site_categories

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  def show
    @products = @brand.products
    if params[:sort]
      @products_c = @brand.products.order(params[:sort]).all
      @products = @products_c.paginate(:page => params[:page], :per_page => 24)
    else 
      @products_c = @brand.products
      @products = @products_c.paginate(:page => params[:page], :per_page => 24)
    end
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      redirect_to @brand, notice: 'Brand was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /brands/1
  def update
    if @brand.update(brand_params)
      redirect_to @brand, notice: 'Brand was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /brands/1
  def destroy
    @brand.destroy
    redirect_to brands_url, notice: 'Brand was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def brand_params
      params.require(:brand).permit(:name)
    end
end

app/views/brands/_form.html.haml
= form_for @brand do |f|
  - if @brand.errors.any?
    #error_explanation
      %h2= "#{pluralize(@brand.errors.count, "error")} prohibited this brand from being saved:"
      %ul
        - @brand.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/brands/edit.html.haml
%h1 Editing brand

= render 'form'

= link_to 'Show', @brand
\|
= link_to 'Back', brands_path

app/views/brands/index.html.haml
%h1 Listing brands

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @brands.each do |brand|
      %tr
        %td= brand.name
        %td= link_to 'Show', brand
        %td= link_to 'Edit', edit_brand_path(brand)
        %td= link_to 'Destroy', brand, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Brand', new_brand_path

app/views/brands/new.html.haml
%h1 New brand

= render 'form'

= link_to 'Back', brands_path

app/views/brands/show.html.haml
#category_header
  %h1= @brand.name

  #filters

    - if params[:sort] && params[:sort][:id] == "desc"
      = link_to "DATE &#8595;".html_safe, brand_path(@brand, sort: {id: :asc}), class: "filter_link"
    - elsif params[:sort] && params[:sort][:id] == "asc"
      = link_to "DATE &#8593;".html_safe, brand_path(@brand, sort: {id: :desc}), class: "filter_link"
    - else
      = link_to "DATE", brand_path(@brand, sort: {id: :desc}), class: "filter_link"

    - if params[:sort] && params[:sort][:name] == "desc"
      = link_to "NAME &#8595;".html_safe, brand_path(@brand, sort: {name: :asc}), class: "filter_link"
    - elsif params[:sort] && params[:sort][:name] == "asc"
      = link_to "NAME &#8593;".html_safe, brand_path(@brand, sort: {name: :desc}), class: "filter_link"
    - else
      = link_to "NAME", brand_path(@brand, sort: {name: :desc}), class: "filter_link"

    - if params[:sort] && params[:sort][:price] == "desc"
      = link_to "PRICE &#8595;".html_safe, brand_path(@brand, sort: {price: :asc}), class: "filter_link"
    - elsif params[:sort] && params[:sort][:price] == "asc"
      = link_to "PRICE &#8593;".html_safe, brand_path(@brand, sort: {price: :desc}), class: "filter_link"
    - else
      = link_to "PRICE", brand_path(@brand, sort: {price: :desc}), class: "filter_link"


= render 'layouts/product_list'